apiVersion: 'kubeflow.org/v1'
kind: 'PyTorchJob'
metadata:
  name: 'pytorch-dist-mnist-gloo'
  namespace: 'default'
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - name: pytorch
              image: gcr.io/dsd-demo-370521/pytorch-dis-mnist:4.0
              args: ['--backend', 'gloo', '--epochs', '5']
              volumeMounts:
                - name: savedmodel
                  mountPath: /savedmodel/fds
          volumes:
            - name: savedmodel
              persistentVolumeClaim:
                claimName: pv-ogbl-claim

    Worker:
      replicas: 4
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - name: pytorch
              image: gcr.io/dsd-demo-370521/pytorch-dis-mnist:4.0
              args: ['--backend', 'gloo', '--epochs', '5']
