steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'gcr.io/dsd-demo-370521/pytorch-distributed-ogbl:1.0',
        '-f',
        'ogbl.Dockerfile',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/dsd-demo-370521/pytorch-distributed-ogbl:1.0']
