apiVersion: 'kubeflow.org/v1'
kind: 'PyTorchJob'
metadata:
  name: 'm-1-w-7-e-10-pytorch-dist-ogbl-gloo'
  namespace: 'default'
spec:
  pytorchReplicaSpecs:
    Master:
      replicas: 1
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - name: pytorch
              image: gcr.io/dsd-demo-370521/pytorch-distributed-ogbl:1.0
              imagePullPolicy: Always
              args:
                [
                  '--backend',
                  'gloo',
                  '--epochs',
                  '10',
                  '--exp-name',
                  'm-1-w-7-e-10',
                ]
              volumeMounts:
                - name: savedmodel
                  mountPath: /app/src/tensorboard
          volumes:
            - name: savedmodel
              persistentVolumeClaim:
                claimName: nfs

    Worker:
      replicas: 7
      restartPolicy: OnFailure
      template:
        metadata:
          annotations:
            sidecar.istio.io/inject: 'false'
        spec:
          containers:
            - name: pytorch
              image: gcr.io/dsd-demo-370521/pytorch-distributed-ogbl:1.0
              imagePullPolicy: Always
              args:
                [
                  '--backend',
                  'gloo',
                  '--epochs',
                  '10',
                  '--exp-name',
                  'm-1-w-7-e-10',
                ]
              volumeMounts:
                - name: savedmodel
                  mountPath: /app/src/tensorboard
          volumes:
            - name: savedmodel
              persistentVolumeClaim:
                claimName: nfs
